---
on: [push, pull_request]

jobs:
  terraform_plan:
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Terraform Init
        run:
          terraform init
      - name: Terraform Plan
        run:
          terraform plan tests/integration