---
on: [push, pull_request]

jobs:
  terraform_plan:
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Terraform Init
        run:
          terraform init -input=false tests/integration
      - name: Terraform Plan
        run:
          terraform plan -out=tfplan tests/integration